version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: "lockfile-only"
    commit-message:
      prefix: "dependency update"
      include: "scope"
